name: Build and deploy ASP.Net Core app to Azure Web App - devportfolio-api-manish2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore DevPortfolio.API/DevPortfolio.API.csproj

      - name: Build with dotnet
        run: dotnet build DevPortfolio.API/DevPortfolio.API.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish DevPortfolio.API/DevPortfolio.API.csproj --configuration Release --no-build -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05D062E7C00C4D9F84814692B187B0A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED9ED277E0E74C719F5384F789C80C6B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BEABF37E706454BA51D65788CEBC90D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devportfolio-api-manish2026'
          slot-name: 'Production'
          package: ./publish
